name: tts-finetune-hf
channels:
  - defaults
dependencies:
  - python==3.12
  - pip
  - numpy<2
  - pyyaml
  - matplotlib
  - jupyter
  - pytest
  - tqdm

  - pip:
    - transformers
    - datasets
    - soundfile
    - speechbrain
    - accelerate


#To install PyTorch, follow instructions below
 #conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia

#Please install the files below as well
#conda install -c conda-forge libsndfile
#conda install "ffmpeg"
#pip install jiwer
#pip install librosa




